# See https://pre-commit.com/ for usage and config
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: mdformat
        name: mdformat
        stages: [commit]
        language: system
        entry: poetry run mdformat --wrap 88
        types: [markdown]

      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort --jobs=0 src/normcap src/tests/
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black src/normcap src/tests/
        types: [python]

      - id: pydocstyle
        name: pydocstyle
        stages: [commit]
        language: system
        entry: poetry run pydocstyle src/normcap src/tests/
        types: [python]
        pass_filenames: false

      - id: pylint
        name: pylint
        stages: [commit]
        language: system
        entry: poetry run pylint src/normcap src/tests
        types: [python]
        pass_filenames: false

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: poetry run mypy
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry:
          poetry run pytest --log-cli-level=10 src/tests/ --cov normcap
          --cov-report xml:cov.xml --cov-report html
        types: [python]
        pass_filenames: false

      - id: pydeps
        name: pydeps
        stages: [commit]
        language: system
        entry:
          poetry run pydeps src/normcap --max-bacon=1 --cluster
          --max-cluster-size=1 --no-show -o=dependency_graph.png -T=png
        types: [python]
        pass_filenames: false
